server:
port: 8080

mybatis:
#mapper??????
mapper-locations: classpath:/mapper/*.xml
# ????????
type-aliases-package: com.test.sharding.domain.pojo
configuration:
# ?????? Ming == m_ing
map-underscore-to-camel-case: true

spring:
main:
allow-bean-definition-overriding: true
application:
name: sharding-jdbc-test
shardingsphere:
props:
sql:
show: true
datasource:
names: db1
db1:
type: com.alibaba.druid.pool.DruidDataSource
#mysql??
driver-class-name: com.mysql.cj.jdbc.Driver
url: jdbc:mysql://localhost:3306/sharding-jdbc-test?useUnicode=true&characterEncoding=utf8&useSSL=false
username: root
password: root
sharding:
tables:
#scs_product???????sql?????????????????????
# ????scs_product_1  ? scs_product_2  ???scs_product???
# ???sql???scs_product?sharding-jdbc??????????
scs_product:
actual-data-nodes: db1.scs_product_$->{1..2}
# ???????????id,????
key-generator:
column: PRODUCT_ID
type: SNOWFLAKE
#??scs_product???????  ???????? ?????????
table-strategy:
inline:
# ????scs_product_1  ????scs_product_2
# ?????????????????????????
# ??????????????????????????????
algorithm-expression: scs_product_$->{PRODUCT_ID % 2 + 1}
# ??????PRODUCT_ID
sharding-column: PRODUCT_ID